#!/usr/bin/bash
#PBS -l walltime=100:00:00
#PBS -l mem=192Gb
#PBS -l ncpus=24
#PBS -l select=cputype=sapphirerapids
#PBS -j oe
set -e

lscpu

cd "${PBS_O_WORKDIR}"

module add crest
module add orca

/srv/scratch/${USER}/censo/bin/censo -i crest_conformers.xyz --maxcores 24 -O 1 --loglevel DEBUG > censo.out
